#!/usr/bin/env bash
# write script transfer a file from client to server
# $#:args $1:file to cp $2:ip $3:username $4:private ssh key

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
