#!/usr/bin/env bash
#install nginx listening on port 80 and show hello world on requesting a page

sudo apt-get update
sudo apt-get install -y nginx

sed -i "s/listen [0-9]*;/listen 80;/g" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
