#!/usr/bin/env bash
#install nginx listening on port 80 and show hello world on requesting a page

sudo apt-get update
sudo apt-get install -y nginx

redirect_confg="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s/server_name _;/$redirect_confg/" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo nginx -t
