#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/listen [0-9]*/listen 80/" /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
