#!/usr/bin/env bash
#blocks all incoming traffic, except SSH/TCP, HTTP SSL/TCP and HTTP/TCP
sudo apt-get install ufw -y

sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
